### PR TITLE
Fixed dead Spigot link

### PR DESCRIPTION
**Pull request by HunterGPlays**
I made your ant.get for spigot link to my repo instead. The o2gaming one was dead.

### CODE REVIEW

**Comment by stuntguy3000** [comment]
Can I recommend something more _reputable?_ (e.g. spigotdl.com)

**Comment by HunterGPlays** [comment]
This should be better

**Comment by libraryaddict** [comment]
Sorry but going back to maven

**Comment by stuntguy3000** [comment]
Good call @libraryaddict

**Pull request closed without merging**
