### PR TITLE
Adds option to enable/disable protocol lib auto update

### PR DESCRIPTION
**Pull request by camdenorrb**
Title says all

### CODE REVIEW

**Comment by libraryaddict** [comment]
Lib's Disguises will only update ProtocolLib if you are using a version that cannot work.

**Comment by camdenorrb** [comment]
@libraryaddict not in all cases, for example I made a fork of protocollib

**Comment by libraryaddict** [comment]
Can you give me a link?

**Comment by libraryaddict** [comment]
Possible to provide your compiled ProtocolLib.jar? The issue is likely in the version

**Comment by camdenorrb** [comment]
https://github.com/camdenorrb/ProtocolLib/releases/download/v1.0.0/ProtocolLib.jar

ignore the release version, not relevant

plugin.yml: 5.0.0-SNAPSHOT

**Pull request closed without merging**
